<?php
include_once("../../Dao/BaseDao.php");
class LucroVendasDao extends BaseDao
{
    function LucroVendasDao(){
        $this->conect();
    }

    function DadosComissao($codClienteFinal){               
        $sql_lista = "SELECT STRAIGHT_JOIN COD_VENDA,
                             DTA_VENDA,
                             DSC_PRODUTO,
                             COALESCE(DSC_MARCA,'') AS DSC_MARCA,
                             VLR_VENDA,
                             VLR_DESCONTO,
                             VLR_VENDA-VLR_DESCONTO AS VLR_COM_DESCONTO,
                             QTD_VENDIDA,	
                             VLR_VENDA_PRODUTO,	   
                             VLR_UNITARIO AS VLR_CUSTO,
							 VLR_LUCRO_UNITARIO,
                             #(VLR_VENDA_PRODUTO-(VLR_UNITARIO*QTD_VENDIDA))-(VLR_IMPOSTO*VLR_VENDA_PRODUTO)-(VLR_VENDA_PRODUTO*VLR_PORCENTAGEM_VENDA/100)-(VLR_VENDA_PRODUTO*VLR_PORCENTAGEM_FUNCIONARIO/100)-VLR_PORCENTAGEM_PAGAMENTO AS VLR_LUCRO_UNITARIO,
                             VLR_LUCRO_VENDA,
                             VLR_PORCENTAGEM_PAGAMENTO,
                             VLR_TOTAL_VENDA,
							 VLR_PORCENTAGEM_LUCRO_VENDA,							 
                             VLR_IMPOSTO,
                             VLR_IMPOSTO*VLR_VENDA_PRODUTO AS VLR_IMPOSTO_CALCULADO,
                             VLR_PORCENTAGEM_VENDA,
                             VLR_PORCENTAGEM_VENDA AS VLR_COMISSAO_VENDEDOR,
                             VLR_VENDA_PRODUTO*VLR_PORCENTAGEM_FUNCIONARIO/100 AS VLR_COMISSAO_FUNCIONARIO,
                             DSC_CLIENTE,
                             DSC_VEICULO,
                             NME_VENDEDOR,
                             NME_FUNCIONARIO
                             #SUM((((VLR_VENDA_PRODUTO-(VLR_UNITARIO*QTD_VENDIDA))-(VLR_IMPOSTO*VLR_VENDA_PRODUTO)-(VLR_VENDA_PRODUTO*VLR_PORCENTAGEM_VENDA/100)-(VLR_VENDA_PRODUTO*VLR_PORCENTAGEM_FUNCIONARIO/100)-VLR_PORCENTAGEM_PAGAMENTO) /VLR_VENDA_PRODUTO)*100) AS VLR_PORCENTAGEM_LUCRO_VENDA
                        FROM
                     (SELECT V.COD_VENDA,
                             V.DTA_VENDA,
                             CASE WHEN P.TPO_PRODUTO='P' THEN V.VLR_IMPOSTO_PRODUTO ELSE V.VLR_IMPOSTO_SERVICO END AS VLR_IMPOSTO,
                             P.DSC_PRODUTO,
                             P.TPO_PRODUTO,
                             M.DSC_MARCA,
                             COALESCE(P.VLR_PORCENTAGEM,0) AS VLR_PORCENTAGEM,
                             CASE WHEN P.TPO_PRODUTO='S' THEN (CASE WHEN (P.IND_COMISSAO_GERENCIA='S') THEN COALESCE(UF.VLR_PORCENTAGEM_GERENCIA,0) ELSE COALESCE(UF.VLR_PORCENTAGEM_SERVICO,0) END) ELSE 0 END AS VLR_PORCENTAGEM_FUNCIONARIO,
                             VP.VLR_VENDA,
                             VP.VLR_DESCONTO,
                             VP.QTD_VENDIDA,
                            (VP.VLR_VENDA-VP.VLR_DESCONTO)*VP.QTD_VENDIDA AS VLR_VENDA_PRODUTO,	   
                             COALESCE(EE.VLR_UNITARIO,0) AS VLR_UNITARIO,
                             COALESCE(C.DSC_CLIENTE,'') AS DSC_CLIENTE,
                             COALESCE(VE.DSC_VEICULO,'') AS DSC_VEICULO,
                             UV.NME_USUARIO_COMPLETO AS NME_VENDEDOR,
                             (SELECT SUM((((VPR.VLR_VENDA-VPR.VLR_DESCONTO)*VPR.QTD_VENDIDA)*COALESCE(UVE.VLR_PORCENTAGEM_VENDA,0))/100)
							   FROM EN_VENDA VE
							  INNER JOIN RE_VENDA_PRODUTO VPR							     
							     ON VE.COD_VENDA = VPR.COD_VENDA
							  INNER JOIN SE_USUARIO UVE
							     ON VE.COD_USUARIO = UVE.COD_USUARIO
							  WHERE VPR.COD_VENDA = V.COD_VENDA
							  GROUP BY VPR.COD_VENDA) AS VLR_PORCENTAGEM_VENDA,
                             UF.NME_USUARIO_COMPLETO AS NME_FUNCIONARIO,
						    (SELECT SUM((COALESCE(TPAG.VLR_PORCENTAGEM,0)/100)*VPAG.VLR_PAGAMENTO) AS VLR_PORCENTAGEM_PAGAMENTO
							  FROM EN_VENDA_PAGAMENTO VPAG 
							 INNER JOIN EN_TIPO_PAGAMENTO TPAG
								ON VPAG.COD_TIPO_PAGAMENTO = TPAG.COD_TIPO_PAGAMENTO
							 WHERE VPAG.COD_VENDA = V.COD_VENDA) AS VLR_PORCENTAGEM_PAGAMENTO,
							(SELECT SUM(((
							           ((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA)-(COALESCE(VLR_UNITARIO,0)*QTD_VENDIDA)-
									   ((CASE WHEN TPO_PRODUTO='P' THEN VLR_IMPOSTO_PRODUTO ELSE VLR_IMPOSTO_SERVICO END)*((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA))-
									   ((((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA)*COALESCE(VLR_PORCENTAGEM_VENDA,0))/100)-
									   ((((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA)*CASE WHEN TPO_PRODUTO='S' THEN (CASE WHEN (IND_COMISSAO_GERENCIA='S') THEN COALESCE(VLR_PORCENTAGEM_GERENCIA,0) ELSE COALESCE(VLR_PORCENTAGEM_SERVICO,0) END) ELSE 0 END)/100)-
									   ((COALESCE(VLR_PORCENTAGEM,0)/100)*VLR_PAGAMENTO)
									   )))
							   FROM 
                                    (SELECT VE.COD_VENDA, VPR.COD_PRODUTO, VPR.VLR_VENDA, VPR.VLR_DESCONTO, VPR.QTD_VENDIDA, PR.TPO_PRODUTO, VE.VLR_IMPOSTO_PRODUTO, VE.VLR_IMPOSTO_SERVICO, PR.IND_COMISSAO_GERENCIA, UFE.VLR_PORCENTAGEM_GERENCIA, UFE.VLR_PORCENTAGEM_SERVICO, TPAGR.VLR_PORCENTAGEM, VPAGR.VLR_PAGAMENTO, UVE.VLR_PORCENTAGEM_VENDA, EER.VLR_UNITARIO
							   FROM EN_VENDA VE
							  INNER JOIN RE_VENDA_PRODUTO VPR
							     ON VE.COD_VENDA = VPR.COD_VENDA
							  INNER JOIN EN_PRODUTO PR
							     ON VPR.COD_PRODUTO = PR.COD_PRODUTO
							  INNER JOIN SE_USUARIO UVE
							     ON VE.COD_USUARIO = UVE.COD_USUARIO
							  INNER JOIN SE_USUARIO UFE
							     ON VPR.COD_FUNCIONARIO = UFE.COD_USUARIO
							  INNER JOIN EN_VENDA_PAGAMENTO VPAGR
							     ON VE.COD_VENDA = VPAGR.COD_VENDA
							  INNER JOIN EN_TIPO_PAGAMENTO TPAGR
							     ON VPAGR.COD_TIPO_PAGAMENTO = TPAGR.COD_TIPO_PAGAMENTO
							   LEFT JOIN EN_ENTRADA_ESTOQUE EER
							     ON VPR.COD_PRODUTO = EER.COD_PRODUTO
								AND VPR.NRO_SEQUENCIAL = EER.NRO_SEQUENCIAL
							  GROUP BY VE.COD_VENDA, VPR.COD_PRODUTO) AS X
							  WHERE X.COD_VENDA = V.COD_VENDA AND X.COD_PRODUTO = VP.COD_PRODUTO) AS VLR_LUCRO_UNITARIO,							 
							(SELECT SUM(((
							           ((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA)-(COALESCE(VLR_UNITARIO,0)*QTD_VENDIDA)-
									   ((CASE WHEN TPO_PRODUTO='P' THEN VLR_IMPOSTO_PRODUTO ELSE VLR_IMPOSTO_SERVICO END)*((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA))-
									   ((((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA)*COALESCE(VLR_PORCENTAGEM_VENDA,0))/100)-
									   ((((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA)*CASE WHEN TPO_PRODUTO='S' THEN (CASE WHEN (IND_COMISSAO_GERENCIA='S') THEN COALESCE(VLR_PORCENTAGEM_GERENCIA,0) ELSE COALESCE(VLR_PORCENTAGEM_SERVICO,0) END) ELSE 0 END)/100)-
									   ((COALESCE(VLR_PORCENTAGEM,0)/100)*VLR_PAGAMENTO)
									   )))
							   FROM 
                                    (SELECT VE.COD_VENDA, VPR.VLR_VENDA, VPR.VLR_DESCONTO, VPR.QTD_VENDIDA, PR.TPO_PRODUTO, VE.VLR_IMPOSTO_PRODUTO, VE.VLR_IMPOSTO_SERVICO, PR.IND_COMISSAO_GERENCIA, UFE.VLR_PORCENTAGEM_GERENCIA, UFE.VLR_PORCENTAGEM_SERVICO, TPAGR.VLR_PORCENTAGEM, VPAGR.VLR_PAGAMENTO, UVE.VLR_PORCENTAGEM_VENDA, EER.VLR_UNITARIO
							   FROM EN_VENDA VE
							  INNER JOIN RE_VENDA_PRODUTO VPR
							     ON VE.COD_VENDA = VPR.COD_VENDA
							  INNER JOIN EN_PRODUTO PR
							     ON VPR.COD_PRODUTO = PR.COD_PRODUTO
							  INNER JOIN SE_USUARIO UVE
							     ON VE.COD_USUARIO = UVE.COD_USUARIO
							  INNER JOIN SE_USUARIO UFE
							     ON VPR.COD_FUNCIONARIO = UFE.COD_USUARIO
							  INNER JOIN EN_VENDA_PAGAMENTO VPAGR
							     ON VE.COD_VENDA = VPAGR.COD_VENDA
							  INNER JOIN EN_TIPO_PAGAMENTO TPAGR
							     ON VPAGR.COD_TIPO_PAGAMENTO = TPAGR.COD_TIPO_PAGAMENTO
							   LEFT JOIN EN_ENTRADA_ESTOQUE EER
							     ON VPR.COD_PRODUTO = EER.COD_PRODUTO
								AND VPR.NRO_SEQUENCIAL = EER.NRO_SEQUENCIAL
							  GROUP BY VE.COD_VENDA, VPR.COD_PRODUTO) AS X
							  WHERE X.COD_VENDA = V.COD_VENDA) AS VLR_LUCRO_VENDA,	

                            (SELECT (SUM((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA)-SUM(COALESCE(VLR_UNITARIO,0)*QTD_VENDIDA)-
									   SUM((CASE WHEN TPO_PRODUTO='P' THEN VLR_IMPOSTO_PRODUTO ELSE VLR_IMPOSTO_SERVICO END)*((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA))-
									   SUM((((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA)*COALESCE(VLR_PORCENTAGEM_VENDA,0))/100)-
									   SUM((((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA)*CASE WHEN TPO_PRODUTO='S' THEN (CASE WHEN (IND_COMISSAO_GERENCIA='S') THEN COALESCE(VLR_PORCENTAGEM_GERENCIA,0) ELSE COALESCE(VLR_PORCENTAGEM_SERVICO,0) END) ELSE 0 END)/100)-
									   SUM((COALESCE(VLR_PORCENTAGEM,0)/100)*VLR_PAGAMENTO)
									   )/SUM((VLR_VENDA-VLR_DESCONTO)*QTD_VENDIDA)*100
							   FROM 
                                    (SELECT VE.COD_VENDA, VPR.VLR_VENDA, VPR.VLR_DESCONTO, VPR.QTD_VENDIDA, PR.TPO_PRODUTO, VE.VLR_IMPOSTO_PRODUTO, VE.VLR_IMPOSTO_SERVICO, PR.IND_COMISSAO_GERENCIA, UFE.VLR_PORCENTAGEM_GERENCIA, UFE.VLR_PORCENTAGEM_SERVICO, TPAGR.VLR_PORCENTAGEM, VPAGR.VLR_PAGAMENTO, UVE.VLR_PORCENTAGEM_VENDA, EER.VLR_UNITARIO
							   FROM EN_VENDA VE
							  INNER JOIN RE_VENDA_PRODUTO VPR
							     ON VE.COD_VENDA = VPR.COD_VENDA
							  INNER JOIN EN_PRODUTO PR
							     ON VPR.COD_PRODUTO = PR.COD_PRODUTO
							  INNER JOIN SE_USUARIO UVE
							     ON VE.COD_USUARIO = UVE.COD_USUARIO
							  INNER JOIN SE_USUARIO UFE
							     ON VPR.COD_FUNCIONARIO = UFE.COD_USUARIO
							  INNER JOIN EN_VENDA_PAGAMENTO VPAGR
							     ON VE.COD_VENDA = VPAGR.COD_VENDA
							  INNER JOIN EN_TIPO_PAGAMENTO TPAGR
							     ON VPAGR.COD_TIPO_PAGAMENTO = TPAGR.COD_TIPO_PAGAMENTO
							   LEFT JOIN EN_ENTRADA_ESTOQUE EER
							     ON VPR.COD_PRODUTO = EER.COD_PRODUTO
								AND VPR.NRO_SEQUENCIAL = EER.NRO_SEQUENCIAL
							  GROUP BY VE.COD_VENDA, VPR.COD_PRODUTO) AS X
							  WHERE X.COD_VENDA = V.COD_VENDA) AS VLR_PORCENTAGEM_LUCRO_VENDA,
							(SELECT SUM(
							           ((VPRE.VLR_VENDA-VPRE.VLR_DESCONTO)*VPRE.QTD_VENDIDA)
									   )
							   FROM RE_VENDA_PRODUTO VPRE							     
							  WHERE VPRE.COD_VENDA = V.COD_VENDA
							  GROUP BY VPRE.COD_VENDA) AS VLR_TOTAL_VENDA
                        FROM EN_VENDA V
                       INNER JOIN EN_CLIENTE C
                          ON V.COD_CLIENTE = C.COD_CLIENTE
                       INNER JOIN RE_VENDA_PRODUTO VP
                          ON V.COD_VENDA = VP.COD_VENDA
                       INNER JOIN EN_PRODUTO P
                          ON VP.COD_PRODUTO = P.COD_PRODUTO
                       INNER JOIN SE_USUARIO UV
                          ON V.COD_USUARIO = UV.COD_USUARIO
                       INNER JOIN SE_USUARIO UF
                          ON VP.COD_FUNCIONARIO = UF.COD_USUARIO
                        LEFT JOIN EN_ENTRADA_ESTOQUE EE
                          ON VP.COD_PRODUTO = EE.COD_PRODUTO
                         AND VP.NRO_SEQUENCIAL = EE.NRO_SEQUENCIAL
                        LEFT JOIN EN_VEICULOS VE
                          ON V.COD_VEICULO = VE.COD_VEICULO
                        LEFT JOIN EN_MARCA M
                          ON P.COD_MARCA = M.COD_MARCA							  
                       WHERE V.DTA_VENDA >= '".$this->ConverteDataForm(filter_input(INPUT_POST, 'dtaVendaInicio', FILTER_SANITIZE_STRING))."'
                         AND V.DTA_VENDA <= '".$this->ConverteDataForm(filter_input(INPUT_POST, 'dtaVendaFim', FILTER_SANITIZE_STRING))."'
                         AND V.COD_CLIENTE_FINAL = $codClienteFinal
                         AND V.NRO_STATUS_VENDA = 'F'
                       GROUP BY V.COD_VENDA, VP.COD_PRODUTO
                       ORDER BY V.COD_VENDA, V.DTA_VENDA) AS X
                       GROUP BY COD_VENDA, DTA_VENDA, DSC_PRODUTO
                       ORDER BY COD_VENDA, DTA_VENDA, DSC_PRODUTO";
        $lista = $this->selectDB("$sql_lista", false);
        return $lista;
    }

}
?>
